# Generated by Django 5.1.15 on 2026-05-31 16:15

import django.db.models.deletion
import uuid
from django.db import migrations, models

from apps.infrastructure.core.migrations._rls_helpers import enable_rls


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('farm_type', models.CharField(choices=[('layer', 'Layer'), ('broiler', 'Broiler'), ('mixed', 'Mixed')], default='mixed', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.organization')),
            ],
            options={
                'db_table': 'farms_farm',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('house_type', models.CharField(choices=[('layer', 'Layer'), ('broiler', 'Broiler'), ('mixed', 'Mixed')], default='mixed', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='houses', to='farms.farm')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.organization')),
            ],
            options={
                'db_table': 'farms_house',
            },
        ),
        migrations.AddIndex(
            model_name='farm',
            index=models.Index(fields=['org', 'is_active'], name='farms_farm_org_id_4f8c3f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='farm',
            unique_together={('org', 'id')},
        ),
        migrations.AddIndex(
            model_name='house',
            index=models.Index(fields=['org', 'farm', 'is_active'], name='farms_house_org_id_4fe725_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='house',
            unique_together={('org', 'farm', 'id')},
        ),
        *enable_rls("farms_farm"),
        *enable_rls("farms_house"),
    ]
