# Generated by Django 5.1.15 on 2026-05-31 15:51

import django.db.models.deletion
import uuid
from django.db import migrations, models

from apps.infrastructure.core.migrations._rls_helpers import disable_rls, enable_rls


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan_tier', models.CharField(choices=[('trial', 'Trial'), ('monthly', 'Monthly'), ('cycle', 'Cycle'), ('yearly', 'Yearly')], max_length=20)),
                ('paystack_plan_code', models.CharField(blank=True, max_length=100)),
                ('amount_kobo', models.IntegerField()),
                ('billing_interval', models.CharField(choices=[('monthly', 'Monthly'), ('annually', 'Annually'), ('per_cycle', 'Per Cycle')], max_length=20)),
                ('features', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'billing_plans',
                'ordering': ['amount_kobo'],
            },
        ),
        *disable_rls("billing_plans"),
        migrations.CreateModel(
            name='PaystackWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('signature_valid', models.BooleanField()),
                ('processed', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'billing_paystackwebhooklog',
                'ordering': ['-received_at'],
            },
        ),
        *disable_rls("billing_paystackwebhooklog"),
        migrations.CreateModel(
            name='CycleSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('paystack_subscription_code', models.CharField(blank=True, max_length=100)),
                ('paystack_email_token', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycle_subscriptions', to='billing.billingplan')),
            ],
            options={
                'db_table': 'billing_cyclesubscription',
            },
        ),
        *enable_rls("billing_cyclesubscription"),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('amount_kobo', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], max_length=10)),
                ('channel', models.CharField(blank=True, max_length=50)),
                ('paystack_transaction_id', models.CharField(blank=True, max_length=100)),
                ('authorization_code', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.organization')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.billingplan')),
            ],
            options={
                'db_table': 'billing_paymentrecord',
                'indexes': [models.Index(fields=['reference'], name='billing_pay_referen_aa4820_idx'), models.Index(fields=['status', 'created_at'], name='billing_pay_status_a38e20_idx')],
            },
        ),
        *enable_rls("billing_paymentrecord"),
    ]
