# Generated by Django 5.1.15 on 2026-06-14 11:35

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_paystackwebhooklog_event_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValuationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broiler_price_per_kg', models.DecimalField(decimal_places=2, default=Decimal('1850.00'), help_text='Fallback ₦/kg for live broiler weight when no market data exists.', max_digits=10)),
                ('layer_point_of_lay_price', models.DecimalField(decimal_places=2, default=Decimal('2800.00'), help_text='Fallback ₦/bird for point-of-lay pullets when no market data exists.', max_digits=10)),
                ('generic_per_bird_price', models.DecimalField(decimal_places=2, default=Decimal('2000.00'), help_text='Fallback ₦/bird for unrecognized bird types.', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Valuation Settings',
                'verbose_name_plural': 'Valuation Settings',
                'db_table': 'billing_valuationsettings',
            },
        ),
    ]
