# Generated by Django 5.1.15 on 2026-06-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchfinancialsummary',
            name='profit_margin_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
