# Generated by Django 5.1.15 on 2026-06-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_seed_seasonal_demand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonaldemandindex',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
