# Generated by Django 5.1.15 on 2026-06-09 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_feedpricereport_hatchery_hatcheryreview'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='feedpricereport',
            new_name='market_feed_feed_ty_7f586a_idx',
            old_name='mkt_feedprice_type_state_date_idx',
        ),
    ]
