# Generated by Django 5.1.15 on 2026-05-31 13:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

from apps.infrastructure.core.migrations._rls_helpers import disable_rls, enable_rls


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('event_type', models.CharField(max_length=60)),
                ('recipient_user_id', models.UUIDField()),
                ('recipient_phone', models.CharField(blank=True, max_length=20)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('body_html', models.TextField(blank=True)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('in_app', 'In-App')], max_length=10)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=15)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('error_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications_outboxevent',
                'indexes': [models.Index(fields=['status', 'created_at'], name='notificatio_status_55d89d_idx'), models.Index(fields=['idempotency_key'], name='notificatio_idempot_e94dc6_idx'), models.Index(fields=['org_id', 'event_type'], name='notificatio_org_id_78c09d_idx')],
            },
        ),
        *disable_rls("notifications_outboxevent"),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('mortality_spike', 'Mortality Spike'), ('water_drop', 'Water Drop'), ('production_drop', 'Production Drop'), ('vaccination_due', 'Vaccination Due'), ('vaccination_overdue', 'Vaccination Overdue'), ('theft_suspected', 'Theft Suspected'), ('heat_stress', 'Heat Stress'), ('heavy_rain', 'Heavy Rain'), ('high_humidity', 'High Humidity'), ('batch_closed', 'Batch Closed'), ('sale_timing', 'Sale Timing'), ('weekly_summary', 'Weekly Summary'), ('incomplete_tasks', 'Incomplete Tasks'), ('disease_outbreak', 'Disease Outbreak'), ('medication_withdrawal', 'Medication Withdrawal')], max_length=60)),
                ('notify_roles', models.JSONField(default=list)),
                ('channels', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('min_severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('cooldown_minutes', models.IntegerField(default=60)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.organization')),
            ],
            options={
                'db_table': 'notifications_alertrule',
                'unique_together': {('org', 'event_type')},
            },
        ),
        *enable_rls("notifications_alertrule"),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=10)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('in_app', 'In-App')], max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('outbox_event_id', models.UUIDField(blank=True, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.organization')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_notificationlog',
                'indexes': [models.Index(fields=['org', 'is_read', 'created_at'], name='notificatio_org_id_60858f_idx')],
            },
        ),
        *enable_rls("notifications_notificationlog"),
    ]
