# Generated by Django 5.1.15 on 2026-06-04 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notificationlog_batch_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrule',
            name='event_type',
            field=models.CharField(choices=[('mortality_spike', 'Mortality Spike'), ('water_drop', 'Water Drop'), ('production_drop', 'Production Drop'), ('vaccination_due', 'Vaccination Due'), ('vaccination_overdue', 'Vaccination Overdue'), ('theft_suspected', 'Theft Suspected'), ('heat_stress', 'Heat Stress'), ('heavy_rain', 'Heavy Rain'), ('high_humidity', 'High Humidity'), ('batch_closed', 'Batch Closed'), ('sale_timing', 'Sale Timing'), ('weekly_summary', 'Weekly Summary'), ('incomplete_tasks', 'Incomplete Tasks'), ('disease_outbreak', 'Disease Outbreak'), ('medication_withdrawal', 'Medication Withdrawal'), ('ai_anomaly', 'AI Anomaly'), ('announcement', 'Announcement')], max_length=60),
        ),
        migrations.CreateModel(
            name='BroadcastNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('audience', models.CharField(choices=[('all', 'All Users'), ('owners', 'Farm Owners Only'), ('managers', 'Managers Only'), ('owners_managers', 'Owners & Managers')], default='owners_managers', max_length=20)),
                ('channel', models.CharField(choices=[('in_app', 'In-App Only'), ('email', 'Email Only'), ('both', 'In-App + Email')], default='both', max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_count', models.IntegerField(default=0)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_broadcastnotification',
                'ordering': ['-sent_at'],
            },
        ),
    ]
