# Generated by Django 5.1.15 on 2026-06-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_alter_alertrule_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboxevent',
            name='idempotency_key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
