# Generated by Django 5.1.15 on 2026-06-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_alter_outboxevent_idempotency_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrule',
            name='event_type',
            field=models.CharField(choices=[('mortality_spike', 'Mortality Spike'), ('water_drop', 'Water Drop'), ('production_drop', 'Production Drop'), ('vaccination_due', 'Vaccination Due'), ('vaccination_overdue', 'Vaccination Overdue'), ('theft_suspected', 'Theft Suspected'), ('heat_stress', 'Heat Stress'), ('heavy_rain', 'Heavy Rain'), ('high_humidity', 'High Humidity'), ('batch_closed', 'Batch Closed'), ('sale_timing', 'Sale Timing'), ('weekly_summary', 'Weekly Summary'), ('incomplete_tasks', 'Incomplete Tasks'), ('disease_outbreak', 'Disease Outbreak'), ('medication_withdrawal', 'Medication Withdrawal'), ('ai_anomaly', 'AI Anomaly'), ('announcement', 'Announcement'), ('support_reply', 'Support Reply'), ('payment_failed', 'Payment Failed'), ('payment_success', 'Payment Success'), ('plan_expired', 'Plan Expired')], max_length=60),
        ),
    ]
