# Generated by Django 5.1.15 on 2026-06-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_impersonationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='impersonationlog',
            name='x_forwarded_for',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
