# Generated by Django 5.1.15 on 2026-06-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_email_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_digest_frequency',
            field=models.CharField(choices=[('daily', 'Daily Summary'), ('weekly', 'Weekly Insights'), ('never', 'Never')], default='weekly', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_financial_reports',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_health_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_production_insights',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_system_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sms_alerts_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
