# Generated by Django 5.1.15 on 2026-06-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_email_digest_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_seen_staff_onboarding',
            field=models.BooleanField(default=False),
        ),
    ]
