# Generated by Django 5.1.15 on 2026-05-31 21:08

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models

from apps.infrastructure.core.migrations._rls_helpers import enable_rls


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        ('flocks', '0002_rename_flocks_batch_org_status_idx_flocks_batc_org_id_96386e_idx_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_date', models.DateField(default=datetime.date.today)),
                ('waste_type', models.CharField(choices=[('litter', 'Litter'), ('dead_birds', 'Dead Birds'), ('packaging', 'Packaging'), ('feed_waste', 'Feed Waste'), ('other', 'Other')], max_length=20)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('disposal_method', models.CharField(choices=[('composting', 'Composting'), ('burning', 'Burning'), ('burial', 'Burial'), ('collection', 'Collection')], default='composting', max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='waste_logs', to='flocks.batch')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='farms.farm')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.organization')),
            ],
            options={
                'db_table': 'waste_wastelog',
                'indexes': [models.Index(fields=['org', 'farm', 'record_date'], name='waste_log_org_farm_date_idx')],
            },
        ),
        # RLS
        *enable_rls("waste_wastelog"),
    ]
