# Generated by Django 5.1.15 on 2026-05-31 21:08

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models

from apps.infrastructure.core.migrations._rls_helpers import enable_rls


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        ('flocks', '0002_rename_flocks_batch_org_status_idx_flocks_batc_org_id_96386e_idx_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_date', models.DateField(default=datetime.date.today)),
                ('feed_type', models.CharField(choices=[('starter', 'Starter'), ('grower', 'Grower'), ('finisher', 'Finisher'), ('layer_mash', 'Layer Mash'), ('chick_mash', 'Chick Mash')], default='layer_mash', max_length=20)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('cost_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True)),
                ('requirement_kg', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=8, null=True)),
                ('variance_kg', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feed_logs', to='flocks.batch')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='farms.farm')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.organization')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feed_feedlog',
                'indexes': [models.Index(fields=['org', 'batch', 'record_date'], name='feed_log_org_batch_date_idx')],
                'unique_together': {('org', 'batch', 'record_date')},
            },
        ),
        migrations.CreateModel(
            name='FeedStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feed_type', models.CharField(choices=[('starter', 'Starter'), ('grower', 'Grower'), ('finisher', 'Finisher'), ('layer_mash', 'Layer Mash'), ('chick_mash', 'Chick Mash')], max_length=20)),
                ('quantity_kg', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('low_stock_threshold_kg', models.DecimalField(decimal_places=2, default=Decimal('50'), max_digits=8)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='farms.farm')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.organization')),
            ],
            options={
                'db_table': 'feed_feedstock',
                'unique_together': {('org', 'farm', 'feed_type')},
            },
        ),
        # RLS
        *enable_rls("feed_feedlog"),
        *enable_rls("feed_feedstock"),
    ]
