# Generated by Django 5.1.15 on 2026-05-31 21:08

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

from apps.infrastructure.core.migrations._rls_helpers import enable_rls


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        ('flocks', '0002_rename_flocks_batch_org_status_idx_flocks_batc_org_id_96386e_idx_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_date', models.DateField(default=datetime.date.today)),
                ('litres_consumed', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('requirement_litres', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=8, null=True)),
                ('variance_litres', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=8, null=True)),
                ('anomaly_flagged', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='water_logs', to='flocks.batch')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='farms.farm')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.organization')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'water_waterlog',
                'indexes': [models.Index(fields=['org', 'batch', 'record_date'], name='water_log_org_batch_date_idx')],
                'unique_together': {('org', 'batch', 'record_date')},
            },
        ),
        # RLS
        *enable_rls("water_waterlog"),
    ]
