# Generated by Django 5.1.15 on 2026-06-11 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0003_alter_waterlog_deleted_by'),
        ('water', '0003_partial_unique_active'),
    ]

    operations = [
    ]
