# Generated by Django 5.1.15 on 2026-05-31 21:23

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

from apps.infrastructure.core.migrations._rls_helpers import enable_rls


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        ('flocks', '0002_rename_flocks_batch_org_status_idx_flocks_batc_org_id_96386e_idx_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drug_name', models.CharField(max_length=200)),
                ('drug_type', models.CharField(choices=[('antibiotic', 'Antibiotic'), ('antiviral', 'Antiviral'), ('antifungal', 'Antifungal'), ('antiparasitic', 'Antiparasitic'), ('vitamin', 'Vitamin'), ('vaccine', 'Vaccine'), ('other', 'Other')], default='antibiotic', max_length=20)),
                ('start_date', models.DateField()),
                ('duration_days', models.IntegerField()),
                ('end_date', models.DateField(editable=False)),
                ('withdrawal_period_days', models.IntegerField(default=0)),
                ('withdrawal_cleared_date', models.DateField(editable=False, null=True)),
                ('dosage', models.CharField(max_length=200)),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit', models.CharField(choices=[('ml', 'ml'), ('g', 'g'), ('tablets', 'Tablets'), ('sachets', 'Sachets')], default='ml', max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vet_name', models.CharField(blank=True, max_length=200)),
                ('reason', models.CharField(choices=[('preventive', 'Preventive'), ('reactive', 'Reactive')], default='reactive', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medications', to='flocks.batch')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='farms.farm')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.organization')),
            ],
            options={
                'db_table': 'health_medicationrecord',
                'indexes': [models.Index(fields=['org', 'batch', 'start_date'], name='health_med_org_batch_start_idx')],
            },
        ),
        migrations.CreateModel(
            name='OutbreakAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disease_name', models.CharField(max_length=200)),
                ('source', models.CharField(choices=[('admin', 'Admin'), ('ai', 'AI')], default='admin', max_length=10)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='farms.farm')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.organization')),
            ],
            options={
                'db_table': 'health_outbreakalert',
                'indexes': [models.Index(fields=['org', 'is_active', 'created_at'], name='health_alert_org_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='SymptomLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_date', models.DateField(default=datetime.date.today)),
                ('affected_count', models.IntegerField()),
                ('symptoms', models.JSONField(default=list)),
                ('diagnosis_result', models.CharField(blank=True, max_length=300)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='mild', max_length=20)),
                ('treatment_notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='symptom_logs', to='flocks.batch')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='farms.farm')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.organization')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_symptomlog',
                'indexes': [models.Index(fields=['org', 'batch', 'record_date'], name='health_sym_org_batch_date_idx')],
            },
        ),
        migrations.CreateModel(
            name='VaccinationSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vaccine_name', models.CharField(max_length=200)),
                ('due_date', models.DateField()),
                ('administered_date', models.DateField(blank=True, null=True)),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('injection', 'Injection'), ('spray', 'Spray'), ('eye_drop', 'Eye Drop'), ('wing_web', 'Wing Web')], default='oral', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('missed', 'Missed'), ('skipped', 'Skipped')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('administered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vaccinations', to='flocks.batch')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='farms.farm')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.organization')),
            ],
            options={
                'db_table': 'health_vaccinationschedule',
                'indexes': [models.Index(fields=['org', 'due_date', 'status'], name='health_vacc_due_status_idx'), models.Index(fields=['org', 'batch', 'status'], name='health_vacc_batch_status_idx')],
            },
        ),
        # RLS
        *enable_rls("health_vaccinationschedule"),
        *enable_rls("health_medicationrecord"),
        *enable_rls("health_symptomlog"),
        *enable_rls("health_outbreakalert"),
    ]
