# Generated by Django 5.1.15 on 2026-05-31 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='batch',
            new_name='flocks_batc_org_id_96386e_idx',
            old_name='flocks_batch_org_status_idx',
        ),
        migrations.RenameIndex(
            model_name='batch',
            new_name='flocks_batc_org_id_a4a22b_idx',
            old_name='flocks_batch_org_farm_status_idx',
        ),
        migrations.RenameIndex(
            model_name='mortalitylog',
            new_name='flocks_mort_org_id_91f9cb_idx',
            old_name='flocks_mortalitylog_org_batch_date_idx',
        ),
        migrations.RenameIndex(
            model_name='mortalitylog',
            new_name='flocks_mort_org_id_c46b1f_idx',
            old_name='flocks_mortalitylog_org_date_idx',
        ),
        migrations.RenameIndex(
            model_name='weightrecord',
            new_name='flocks_weig_org_id_d21aae_idx',
            old_name='flocks_weightrecord_org_batch_idx',
        ),
    ]
