# Generated by Django 5.1.15 on 2026-06-14 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flocks', '0006_alter_batch_deleted_by_alter_mortalitylog_deleted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='valuation_override_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional: override the estimated value per kg (broiler) or per bird (layer/other) for this batch — e.g. if you have a confirmed buyer price.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='valuation_override_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='valuation_override_set_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batch',
            name='valuation_override_unit',
            field=models.CharField(blank=True, choices=[('kg', 'Per kg'), ('bird', 'Per bird')], max_length=10, null=True),
        ),
    ]
