# Generated by Django 5.1.15 on 2026-06-21 15:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_alter_farm_deleted_by_alter_house_deleted_by'),
        ('flocks', '0007_batch_valuation_override_per_unit_and_more'),
        ('market', '0007_feedpricereport_hatchery_country'),
        ('tenants', '0009_organization_country'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active'), ('is_deleted', False)), fields=('org', 'house'), name='unique_active_batch_per_house'),
        ),
    ]
