[program:flockiq-beat]
command=/www/wwwroot/flockiq/venv/bin/celery
    -A config beat
    --loglevel=warning
    --scheduler django_celery_beat.schedulers:DatabaseScheduler
    --pidfile=/var/run/celerybeat.pid
directory=/www/wwwroot/flockiq
user=www
autostart=true
autorestart=true
startsecs=10
environment=DJANGO_SETTINGS_MODULE="config.settings.production"
stderr_logfile=/www/wwwroot/flockiq/logs/celery-beat.err.log
stdout_logfile=/www/wwwroot/flockiq/logs/celery-beat.out.log
