[program:flockiq-celery]
command=/www/wwwroot/flockiq/venv/bin/celery
    -A config worker
    --loglevel=warning
    --concurrency=3
    --queues=default,notifications,weather,tasks
    --hostname=worker@%%h
    --max-tasks-per-child=200
directory=/www/wwwroot/flockiq
user=www
autostart=true
autorestart=true
startsecs=10
stopasgroup=true
killasgroup=true
environment=DJANGO_SETTINGS_MODULE="config.settings.production"
stderr_logfile=/www/wwwroot/flockiq/logs/celery.err.log
stdout_logfile=/www/wwwroot/flockiq/logs/celery.out.log
