# Generated by Django 5.1.15 on 2026-06-04 21:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('tenants', '0003_organization_grace_period_ends_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDailyBrief',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('brief_date', models.DateField()),
                ('overall_status', models.CharField(choices=[('optimal', 'Optimal'), ('attention', 'Needs Attention'), ('critical', 'Critical'), ('warning', 'Warning')], default='optimal', max_length=20)),
                ('headline', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('alerts', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('patterns_detected', models.JSONField(default=list)),
                ('metrics_snapshot', models.JSONField(default=dict)),
                ('critical_count', models.IntegerField(default=0)),
                ('warning_count', models.IntegerField(default=0)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_briefs', to='tenants.organization')),
            ],
            options={
                'ordering': ['-brief_date'],
                'indexes': [models.Index(fields=['org', 'brief_date'], name='analytics_a_org_id_844c1b_idx')],
                'unique_together': {('org', 'brief_date')},
            },
        ),
    ]
