# Generated by Django 5.1.15 on 2026-05-31 12:43

import uuid
from django.db import migrations, models

from apps.infrastructure.core.migrations._rls_helpers import disable_rls


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('subdomain', models.SlugField(max_length=63, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='org_logos/')),
                ('primary_colour', models.CharField(default='#16a34a', max_length=7)),
                ('plan_tier', models.CharField(choices=[('trial', 'Trial'), ('monthly', 'Monthly'), ('cycle', 'Cycle'), ('yearly', 'Yearly')], default='trial', max_length=20)),
                ('subscription_status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('trial', 'Trial')], default='trial', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=200)),
                ('owner_phone', models.CharField(blank=True, max_length=20)),
                ('owner_email', models.EmailField(blank=True, max_length=254)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenants_organization',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['subdomain'], name='tenants_org_subdoma_d47977_idx'), models.Index(fields=['subscription_status'], name='tenants_org_subscri_24f65d_idx')],
            },
        ),
        # Organization is the tenant root — RLS must be OFF.
        # TenantMiddleware, auth, and Celery fan-out tasks all query this table
        # cross-tenant BEFORE any org context is established.
        *disable_rls("tenants_organization"),
    ]
