# Generated by Django 5.1.15 on 2026-06-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='onboarding_complete',
            field=models.BooleanField(default=False),
        ),
    ]
