# Generated by Django 5.1.15 on 2026-06-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_organization_onboarding_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='grace_period_ends_at',
            field=models.DateTimeField(blank=True, help_text='If set, org has billing grace period until this date', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='max_users',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='organization',
            name='storage_quota_gb',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='organization',
            name='subscription_status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('trial', 'Trial'), ('past_due', 'Past Due')], default='trial', max_length=20),
        ),
    ]
