# Generated by Django 5.1.15 on 2026-06-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_organization_custom_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='subscription_status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('trial', 'Trial'), ('past_due', 'Past Due'), ('lapsed', 'Lapsed')], default='trial', max_length=20),
        ),
    ]
