# Generated by Django 5.1.15 on 2026-06-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_whatsapp', models.CharField(default='2348000000000', help_text='WhatsApp number with country code, no + or spaces. e.g. 2348012345678', max_length=20)),
                ('admin_email', models.EmailField(default='admin@flockiq.com', max_length=254)),
                ('admin_phone', models.CharField(blank=True, default='', max_length=20)),
                ('bank_name', models.CharField(blank=True, default='', help_text='e.g. GTBank, Zenith Bank', max_length=100)),
                ('bank_account_number', models.CharField(blank=True, default='', max_length=20)),
                ('bank_account_name', models.CharField(blank=True, default='', help_text='e.g. ADM Tech Hub Limited', max_length=200)),
                ('company_name', models.CharField(default='FlockIQ / ADM Tech Hub', max_length=200)),
                ('support_hours', models.CharField(blank=True, default='Mon–Fri, 8AM–6PM WAT', max_length=100)),
            ],
            options={
                'verbose_name': 'Platform Configuration',
                'verbose_name_plural': 'Platform Configuration',
            },
        ),
    ]
