# Generated by Django 5.1.15 on 2026-05-31 20:50

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models

from apps.infrastructure.core.migrations._rls_helpers import enable_rls


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        ('flocks', '0002_rename_flocks_batch_org_status_idx_flocks_batc_org_id_96386e_idx_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrateInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('crates_produced', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8)),
                ('crates_sold', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8)),
                ('crates_balance', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='farms.farm')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.organization')),
            ],
            options={
                'db_table': 'production_crateinventory',
                'unique_together': {('org', 'farm', 'date')},
            },
        ),
        migrations.CreateModel(
            name='EggProductionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_date', models.DateField(default=datetime.date.today)),
                ('total_eggs', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('grade_a', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('grade_b', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('grade_c', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('broken', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('hen_day_pct', models.DecimalField(decimal_places=2, editable=False, max_digits=5, null=True)),
                ('crates', models.DecimalField(decimal_places=1, editable=False, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='egg_logs', to='flocks.batch')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='farms.farm')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='farms.house')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.organization')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'production_eggproductionlog',
                'indexes': [models.Index(fields=['org', 'batch', 'record_date'], name='prod_egg_org_batch_date_idx'), models.Index(fields=['org', 'record_date'], name='prod_egg_org_date_idx')],
                'unique_together': {('org', 'batch', 'record_date')},
            },
        ),
        # RLS
        *enable_rls("production_crateinventory"),
        *enable_rls("production_eggproductionlog"),
    ]
