# Generated by Django 5.1.15 on 2026-06-11 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_alter_eggproductionlog_deleted_by'),
        ('production', '0004_partial_unique_active'),
    ]

    operations = [
    ]
